services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env # Use the .env file from the 'api' directory

    ports:
      - "4000:4000"
    depends_on:
      - db
    networks:
      - simplifiednetwork

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - simplifiednetwork

  db:
    image: postgres:13
    env_file:
      - ./api/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - simplifiednetwork

volumes:
  db_data:

networks:
  simplifiednetwork:
    driver: bridge
