export const USERS = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    password: "password123",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    password: "password456",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    password: "password789",
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    password: "password321",
  },
  {
    firstName: "Christopher",
    lastName: "Brown",
    email: "christopher.brown@example.com",
    password: "password654",
  },
  {
    firstName: "Jessica",
    lastName: "Taylor",
    email: "jessica.taylor@example.com",
    password: "password987",
  },
  {
    firstName: "Daniel",
    lastName: "Anderson",
    email: "daniel.anderson@example.com",
    password: "password147",
  },
  {
    firstName: "Sarah",
    lastName: "Thomas",
    email: "sarah.thomas@example.com",
    password: "password258",
  },
  {
    firstName: "Matthew",
    lastName: "Jackson",
    email: "matthew.jackson@example.com",
    password: "password369",
  },
  {
    firstName: "Ashley",
    lastName: "White",
    email: "ashley.white@example.com",
    password: "password741",
  },
  {
    firstName: "Joshua",
    lastName: "Harris",
    email: "joshua.harris@example.com",
    password: "password852",
  },
  {
    firstName: "Amanda",
    lastName: "Martin",
    email: "amanda.martin@example.com",
    password: "password963",
  },
  {
    firstName: "David",
    lastName: "Thompson",
    email: "david.thompson@example.com",
    password: "password1234",
  },
  {
    firstName: "Laura",
    lastName: "Garcia",
    email: "laura.garcia@example.com",
    password: "password5678",
  },
  {
    firstName: "James",
    lastName: "Martinez",
    email: "james.martinez@example.com",
    password: "password9012",
  },
  {
    firstName: "Elizabeth",
    lastName: "Robinson",
    email: "elizabeth.robinson@example.com",
    password: "password3456",
  },
  {
    firstName: "Andrew",
    lastName: "Clark",
    email: "andrew.clark@example.com",
    password: "password7890",
  },
  {
    firstName: "Megan",
    lastName: "Rodriguez",
    email: "megan.rodriguez@example.com",
    password: "password1122",
  },
  {
    firstName: "William",
    lastName: "Lewis",
    email: "william.lewis@example.com",
    password: "password3344",
  },
  {
    firstName: "Olivia",
    lastName: "Lee",
    email: "olivia.lee@example.com",
    password: "password5566",
  },
];

export const PROJECTS = [
  {
    name: "Project Alpha",
    description: "Initial project phase.",
    category: "Development",
    price: 15000,
    managerId: 1,
    status: "ONGOING",
  },
  {
    name: "Project Beta",
    description: "Beta testing phase.",
    category: "Testing",
    price: 12000,
    managerId: 5,
    status: "DELAYED",
  },
  {
    name: "Project Gamma",
    description: "Gamma release.",
    category: "Release",
    price: 20000,
    managerId: 3,
    status: "COMPLETED",
  },
  {
    name: "Project Delta",
    description: "Delta improvements.",
    category: "Maintenance",
    price: 11000,
    managerId: 7,
    status: "AT_RISK",
  },
  {
    name: "Project Epsilon",
    description: "Epsilon enhancements.",
    category: "Development",
    price: 14000,
    managerId: 9,
    status: "ONGOING",
  },
  {
    name: "Project Zeta",
    description: "Zeta integration.",
    category: "Integration",
    price: 17000,
    managerId: 2,
    status: "DELAYED",
  },
  {
    name: "Project Eta",
    description: "Eta optimization.",
    category: "Optimization",
    price: 16000,
    managerId: 4,
    status: "COMPLETED",
  },
  {
    name: "Project Theta",
    description: "Theta migration.",
    category: "Migration",
    price: 13000,
    managerId: 6,
    status: "AT_RISK",
  },
  {
    name: "Project Iota",
    description: "Iota upgrade.",
    category: "Upgrade",
    price: 18000,
    managerId: 8,
    status: "ONGOING",
  },
  {
    name: "Project Kappa",
    description: "Kappa refactoring.",
    category: "Refactoring",
    price: 19000,
    managerId: 10,
    status: "DELAYED",
  },
  {
    name: "Project Lambda",
    description: "Lambda development.",
    category: "Development",
    price: 21000,
    managerId: 11,
    status: "COMPLETED",
  },
  {
    name: "Project Mu",
    description: "Mu testing.",
    category: "Testing",
    price: 11500,
    managerId: 12,
    status: "AT_RISK",
  },
  {
    name: "Project Nu",
    description: "Nu deployment.",
    category: "Deployment",
    price: 22000,
    managerId: 13,
    status: "ONGOING",
  },
  {
    name: "Project Xi",
    description: "Xi feature addition.",
    category: "Development",
    price: 23000,
    managerId: 14,
    status: "DELAYED",
  },
  {
    name: "Project Omicron",
    description: "Omicron support.",
    category: "Support",
    price: 12500,
    managerId: 15,
    status: "COMPLETED",
  },
  {
    name: "Project Pi",
    description: "Pi optimization.",
    category: "Optimization",
    price: 14500,
    managerId: 16,
    status: "AT_RISK",
  },
  {
    name: "Project Rho",
    description: "Rho migration.",
    category: "Migration",
    price: 16500,
    managerId: 17,
    status: "ONGOING",
  },
  {
    name: "Project Sigma",
    description: "Sigma integration.",
    category: "Integration",
    price: 18500,
    managerId: 18,
    status: "DELAYED",
  },
  {
    name: "Project Tau",
    description: "Tau upgrade.",
    category: "Upgrade",
    price: 19500,
    managerId: 19,
    status: "COMPLETED",
  },
  {
    name: "Project Upsilon",
    description: "Upsilon refactoring.",
    category: "Refactoring",
    price: 20500,
    managerId: 20,
    status: "AT_RISK",
  },
  {
    name: "Project Phi",
    description: "Phi development.",
    category: "Development",
    price: 12500,
    managerId: 1,
    status: "ONGOING",
  },
  {
    name: "Project Chi",
    description: "Chi testing.",
    category: "Testing",
    price: 13500,
    managerId: 2,
    status: "DELAYED",
  },
  {
    name: "Project Psi",
    description: "Psi deployment.",
    category: "Deployment",
    price: 14500,
    managerId: 3,
    status: "COMPLETED",
  },
];
