export const USERS = [
  {
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    password: "password123",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    password: "password456",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    email: "michael.johnson@example.com",
    password: "password789",
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    email: "emily.davis@example.com",
    password: "password321",
  },
  {
    firstName: "Christopher",
    lastName: "Brown",
    email: "christopher.brown@example.com",
    password: "password654",
  },
  {
    firstName: "Jessica",
    lastName: "Taylor",
    email: "jessica.taylor@example.com",
    password: "password987",
  },
  {
    firstName: "Daniel",
    lastName: "Anderson",
    email: "daniel.anderson@example.com",
    password: "password147",
  },
  {
    firstName: "Sarah",
    lastName: "Thomas",
    email: "sarah.thomas@example.com",
    password: "password258",
  },
  {
    firstName: "Matthew",
    lastName: "Jackson",
    email: "matthew.jackson@example.com",
    password: "password369",
  },
  {
    firstName: "Ashley",
    lastName: "White",
    email: "ashley.white@example.com",
    password: "password741",
  },
  {
    firstName: "Joshua",
    lastName: "Harris",
    email: "joshua.harris@example.com",
    password: "password852",
  },
  {
    firstName: "Amanda",
    lastName: "Martin",
    email: "amanda.martin@example.com",
    password: "password963",
  },
  {
    firstName: "David",
    lastName: "Thompson",
    email: "david.thompson@example.com",
    password: "password1234",
  },
  {
    firstName: "Laura",
    lastName: "Garcia",
    email: "laura.garcia@example.com",
    password: "password5678",
  },
  {
    firstName: "James",
    lastName: "Martinez",
    email: "james.martinez@example.com",
    password: "password9012",
  },
  {
    firstName: "Elizabeth",
    lastName: "Robinson",
    email: "elizabeth.robinson@example.com",
    password: "password3456",
  },
  {
    firstName: "Andrew",
    lastName: "Clark",
    email: "andrew.clark@example.com",
    password: "password7890",
  },
  {
    firstName: "Megan",
    lastName: "Rodriguez",
    email: "megan.rodriguez@example.com",
    password: "password1122",
  },
  {
    firstName: "William",
    lastName: "Lewis",
    email: "william.lewis@example.com",
    password: "password3344",
  },
  {
    firstName: "Olivia",
    lastName: "Lee",
    email: "olivia.lee@example.com",
    password: "password5566",
  },
];

export const PROJECTS = [
  {
    name: "Project 1",
    description: "Description for Project 1",
    category: "Category 1",
    price: 5000,
    managerId: 5,
    status: "ONGOING",
    progress: 75,
    dueDate: "2024-08-12",
  },
  {
    name: "Project 2",
    description: "Description for Project 2",
    category: "Category 2",
    price: 70000,
    managerId: 12,
    status: "DELAYED",
    progress: 40,
    dueDate: "2024-07-27",
  },
  {
    name: "Project 3",
    description: "Description for Project 3",
    category: "Category 3",
    price: 30000,
    managerId: 18,
    status: "ONGOING",
    progress: 90,
    dueDate: "2024-10-05",
  },
  {
    name: "Project 4",
    description: "Description for Project 4",
    category: "Category 1",
    price: 25000,
    managerId: 2,
    status: "AT_RISK",
    progress: 20,
    dueDate: "2024-07-30",
  },
  {
    name: "Project 5",
    description: "Description for Project 5",
    category: "Category 4",
    price: 45000,
    managerId: 10,
    status: "COMPLETED",
    progress: 100,
    dueDate: "2024-09-18",
  },
  {
    name: "Project 6",
    description: "Description for Project 6",
    category: "Category 2",
    price: 80000,
    managerId: 14,
    status: "ONGOING",
    progress: 60,
    dueDate: "2024-08-25",
  },
  {
    name: "Project 7",
    description: "Description for Project 7",
    category: "Category 3",
    price: 6000,
    managerId: 7,
    status: "DELAYED",
    progress: 30,
    dueDate: "2024-07-23",
  },
  {
    name: "Project 8",
    description: "Description for Project 8",
    category: "Category 1",
    price: 15000,
    managerId: 19,
    status: "AT_RISK",
    progress: 10,
    dueDate: "2024-07-31",
  },
  {
    name: "Project 9",
    description: "Description for Project 9",
    category: "Category 4",
    price: 35000,
    managerId: 3,
    status: "ONGOING",
    progress: 80,
    dueDate: "2024-09-12",
  },
  {
    name: "Project 10",
    description: "Description for Project 10",
    category: "Category 2",
    price: 40000,
    managerId: 15,
    status: "COMPLETED",
    progress: 95,
    dueDate: "2024-09-30",
  },
  {
    name: "Project 11",
    description: "Description for Project 11",
    category: "Category 3",
    price: 20000,
    managerId: 6,
    status: "ONGOING",
    progress: 50,
    dueDate: "2024-08-08",
  },
  {
    name: "Project 12",
    description: "Description for Project 12",
    category: "Category 1",
    price: 55000,
    managerId: 17,
    status: "DELAYED",
    progress: 45,
    dueDate: "2024-08-05",
  },
  {
    name: "Project 13",
    description: "Description for Project 13",
    category: "Category 4",
    price: 32000,
    managerId: 11,
    status: "AT_RISK",
    progress: 15,
    dueDate: "2024-07-28",
  },
  {
    name: "Project 14",
    description: "Description for Project 14",
    category: "Category 2",
    price: 48000,
    managerId: 4,
    status: "ONGOING",
    progress: 70,
    dueDate: "2024-09-05",
  },
  {
    name: "Project 15",
    description: "Description for Project 15",
    category: "Category 3",
    price: 68000,
    managerId: 16,
    status: "COMPLETED",
    progress: 98,
    dueDate: "2024-09-15",
  },
  {
    name: "Project 16",
    description: "Description for Project 16",
    category: "Category 1",
    price: 23000,
    managerId: 8,
    status: "ONGOING",
    progress: 55,
    dueDate: "2024-08-10",
  },
  {
    name: "Project 17",
    description: "Description for Project 17",
    category: "Category 4",
    price: 42000,
    managerId: 20,
    status: "DELAYED",
    progress: 25,
    dueDate: "2024-08-02",
  },
  {
    name: "Project 18",
    description: "Description for Project 18",
    category: "Category 2",
    price: 26000,
    managerId: 1,
    status: "AT_RISK",
    progress: 5,
    dueDate: "2024-07-25",
  },
  {
    name: "Project 19",
    description: "Description for Project 19",
    category: "Category 3",
    price: 60000,
    managerId: 9,
    status: "ONGOING",
    progress: 85,
    dueDate: "2024-09-08",
  },
  {
    name: "Project 20",
    description: "Description for Project 20",
    category: "Category 1",
    price: 78000,
    managerId: 13,
    status: "COMPLETED",
    progress: 99,
    dueDate: "2024-09-25",
  },
  {
    name: "Project 21",
    description: "Description for Project 21",
    category: "Category 2",
    price: 11000,
    managerId: 5,
    status: "ONGOING",
    progress: 65,
    dueDate: "2024-08-15",
  },
  {
    name: "Project 22",
    description: "Description for Project 22",
    category: "Category 4",
    price: 37000,
    managerId: 12,
    status: "DELAYED",
    progress: 35,
    dueDate: "2024-07-21",
  },
  {
    name: "Project 23",
    description: "Description for Project 23",
    category: "Category 3",
    price: 15000,
    managerId: 18,
    status: "AT_RISK",
    progress: 12,
    dueDate: "2024-07-29",
  },
  {
    name: "Project 24",
    description: "Description for Project 24",
    category: "Category 1",
    price: 52000,
    managerId: 10,
    status: "ONGOING",
    progress: 75,
    dueDate: "2024-09-10",
  },
  {
    name: "Project 25",
    description: "Description for Project 25",
    category: "Category 2",
    price: 45000,
    managerId: 14,
    status: "COMPLETED",
    progress: 92,
    dueDate: "2024-09-28",
  },
  {
    name: "Project 26",
    description: "Description for Project 26",
    category: "Category 3",
    price: 29000,
    managerId: 7,
    status: "ONGOING",
    progress: 55,
    dueDate: "2024-08-02",
  },
  {
    name: "Project 27",
    description: "Description for Project 27",
    category: "Category 1",
    price: 43000,
    managerId: 19,
    status: "DELAYED",
    progress: 42,
    dueDate: "2024-08-08",
  },
  {
    name: "Project 28",
    description: "Description for Project 28",
    category: "Category 4",
    price: 31000,
    managerId: 3,
    status: "AT_RISK",
    progress: 18,
    dueDate: "2024-07-31",
  },
  {
    name: "Project 29",
    description: "Description for Project 29",
    category: "Category 2",
    price: 54000,
    managerId: 15,
    status: "ONGOING",
    progress: 82,
    dueDate: "2024-09-15",
  },
  {
    name: "Project 30",
    description: "Description for Project 30",
    category: "Category 3",
    price: 67000,
    managerId: 6,
    status: "COMPLETED",
    progress: 97,
    dueDate: "2024-09-30",
  },
];
